name: Deploy Node Application

on:
  push:
    branches:
      - mean-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create config.env file
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" > config.env
          echo "PORT=${{ secrets.PORT }}" >> config.env
          echo "USER=${{ secrets.USER }}" >> config.env
          echo "DATABASE=${{ secrets.DATABASE }}" >> config.env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> config.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> config.env
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> config.env
          echo "JWT_COOKIE_EXPIRES_IN=${{ secrets.JWT_COOKIE_EXPIRES_IN }}" >> config.env
          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> config.env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> config.env
          echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> config.env
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> config.env

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t nihalr2001/adventuretrip-nodejs-app .

      - name: Publish image to docker hub
        run: docker push nihalr2001/adventuretrip-nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from docker hub
        run: docker pull nihalr2001/adventuretrip-nodejs-app:latest

      - name: Stop and remove old container if exists
        run: |
          if [ $(docker ps -q -f name=nodejs-app-container) ]; then
            docker stop nodejs-app-container
            docker rm nodejs-app-container
          fi

      - name: Run docker container
        run: |
          docker run -d \
            --name nodejs-app-container \
            -p 3000:3000 \
            --env-file config.env \
            nihalr2001/adventuretrip-nodejs-app:latest
